### ISSUE TITLE
bug: get() returning extra colons

### ISSUE THREAD

**Issue by christianbundy** [omnidan/node-emoji#76]
```javascript
emoji.get('👯‍') // => ':👯‍:'
```

**Comment by emctackett** [comment]
`emoji.get()` is meant to be used with the emoji name rather than the emoji code.

However, we can pretty easily add a guard clause to `get()` to return the emoji code itself if the user passes it in as an argument.  This will prevent the emoji code being returned wrapped in colons.

IMO it is best we address issue #84 first, so that all emoji codes are recognized as expected.  The emoji code used in the above code example, 'dancers', isn't properly recognized at the moment.

**Comment by emctackett** [comment]
Fixed via PR #85 . Closing.
